mod canvas;
mod canvas_prepare_node;
mod canvas_prepare_path;
pub(super) mod modal;
mod panel_bottom;
mod panel_central;
pub(super) mod panel_top;
mod text_editor;
pub(super) mod text_editor_alt;
pub(super) mod window;
pub(super) mod widget;
