[node.Start]
xy = [150, 150]

[node.End]
pivot = "left"
xy = ["Start", "right", 125, 0]

[[path]]
start = ["Start", "top", 0, 0]
end = ["End", "top", 0, 0]
shift = 70
label = ["SingleLineLabel", 1, 100, 0]
label_bg = [255, 135, 135, 255]

[[path]]
start = ["Start", "bottom", 0, 0]
end = ["End", "bottom", 0, 0]
shift = 70
label = ["-----\nMulti\nLine\nLabel\n12345", 1, 100, 37]
label_bg = [255, 135, 135, 255]
