[variables]
s = 325

[[path]]
start = ["Praesent", "right", 0, 0]
end = ["7", "right", 0, 0]
points = [
    ["", "", 1000, "", "", 850],
    ["", "prev", -150, "", "prev", 0],
    ["", "start", 150, "", "start", -150],
    ["imperdiet", "top-right", 0, "imperdiet", "top-right", 0],
    ["", "end", 150, "", "end", -150],
]
shift = 50
z = 8

[node."Praesent"]
value = "444444\n444444\n444444\n444444"
pivot = "left"
xy = [495, 635]
z = 4
size = ["s", "s"]
color = "#E97881FF"

[node."dapibus"]
value = "111111\n111111\n111111\n111111"
xy = ["malesuada", "left", 60, -10]
z = 1
size = ["s", "s"]
color = "#E19A83FF"

[node."enim"]
value = "888888\n888888\n888888\n888888"
xy = [15, 40]
z = 8
size = ["s", "s"]
color = "#F34B7DCF"

[[path]]
start = ["Praesent", "center", 0, 0]
ends = [
    ["dapibus", "center", 0, 0],
    ["malesuada", "center", 0, 0],
    ["3", "center", 0, 0],
    ["Praesent", "center", 0, 0],
    ["imperdiet", "center", 0, 0],
    ["6", "center", 0, 0],
    ["7", "center", 0, 0],
    ["enim", "center", 0, 0],
]
color = "#00627AFF"
z = 4

[node."arcu"]
value = "222222\n222222\n222222\n222222"
xy = [190, 490]
z = 2
size = ["s", "s"]
color = "#E38F82FF"

[node."imperdiet"]
value = "555555\n555555\n555555\n555555"
pivot = "bottom-right"
xy = ["Praesent", "center", 100, 11]
z = 5
size = ["s", "s"]
color = "#EB6D80FF"

[node."malesuada"]
value = "000000\n000000\n000000\n000000"
xy = ["enim", "left", 50, -20]
z = 0
size = ["s", "s"]
color = "#DEA584FF"

[[path]]
start = ["6", "center", 0, 0]
ends = [
    ["dapibus", "center", 0, 0],
    ["malesuada", "center", 0, 0],
    ["3", "center", 0, 0],
    ["Praesent", "center", 0, 0],
    ["7", "center", 0, 0],
    ["enim", "center", 0, 0],
]
color = "#00627AFF"
z = 6

[node.3]
value = "333333\n333333\n333333\n333333"
pivot = "left"
xy = ["arcu", "center", -10, -10]
z = 3
size = ["s", "s"]
color = "#E68381FF"

[node.7]
value = "777777\n777777\n777777\n777777\n"
pivot = "bottom-right"
xy = ["6", "center", 100, 11]
z = 7
size = ["s", "s"]
color = "#F0567EFF"

[node.6]
value = "666666\n666666\n666666\n666666"
pivot = "bottom-right"
xy = [690, 490]
z = 6
size = ["s", "s"]
color = "#EE627FFF"

[[path]]
start = ["malesuada", "center", 0, 0]
ends = [
    ["dapibus", "center", 0, 0],
    ["arcu", "center", 0, 0],
    ["3", "center", 0, 0],
    ["Praesent", "center", 0, 0],
    ["imperdiet", "center", 0, 0],
    ["6", "center", 0, 0],
    ["7", "center", 0, 0],
    ["enim", "center", 0, 0],
]
color = "#00627AFF"
z = 0
